// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.0
// source: quotes_proto/quotes.proto

package quotes_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuotesService_GetQuote_FullMethodName = "/quotes_proto.QuotesService/GetQuote"
)

// QuotesServiceClient is the client API for QuotesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuotesServiceClient interface {
	GetQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
}

type quotesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuotesServiceClient(cc grpc.ClientConnInterface) QuotesServiceClient {
	return &quotesServiceClient{cc}
}

func (c *quotesServiceClient) GetQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, QuotesService_GetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuotesServiceServer is the server API for QuotesService service.
// All implementations must embed UnimplementedQuotesServiceServer
// for forward compatibility.
type QuotesServiceServer interface {
	GetQuote(context.Context, *QuoteRequest) (*QuoteResponse, error)
	mustEmbedUnimplementedQuotesServiceServer()
}

// UnimplementedQuotesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuotesServiceServer struct{}

func (UnimplementedQuotesServiceServer) GetQuote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedQuotesServiceServer) mustEmbedUnimplementedQuotesServiceServer() {}
func (UnimplementedQuotesServiceServer) testEmbeddedByValue()                       {}

// UnsafeQuotesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuotesServiceServer will
// result in compilation errors.
type UnsafeQuotesServiceServer interface {
	mustEmbedUnimplementedQuotesServiceServer()
}

func RegisterQuotesServiceServer(s grpc.ServiceRegistrar, srv QuotesServiceServer) {
	// If the following call pancis, it indicates UnimplementedQuotesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuotesService_ServiceDesc, srv)
}

func _QuotesService_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotesServiceServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuotesService_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotesServiceServer).GetQuote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuotesService_ServiceDesc is the grpc.ServiceDesc for QuotesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuotesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quotes_proto.QuotesService",
	HandlerType: (*QuotesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _QuotesService_GetQuote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quotes_proto/quotes.proto",
}
